#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "yihui's blog"
# Short bio or description (displayed in the header)
description: "辉辉的博客"

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
