#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "yihui's blog"
# Short bio or description (displayed in the header)
description: "辉辉的博客"


